### ISSUE TITLE
nose.proxy.TypeError with ipdb 0.10 or higher

### ISSUE THREAD

**Issue by Fak3** [gotcha/ipdb#103]
Hi. I upgraded ipdb from 0.9.4 to 0.10 and now i can't use ipdb with nosetests. If i do ipdb.set_trace() in any part of the code it crashes on python3 and freezes on python2. 

Sample code:
```
def test11():
    import ipdb; ipdb.set_trace()
    return True

```
Error on python3:

```
======================================================================
ERROR: test.test_11.test11
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/u1/.virtualenvs/npserver/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/z/pproj/npserver_ssh/test/test_11.py", line 13, in test11
    return True
  File "/home/z/pproj/npserver_ssh/test/test_11.py", line 13, in test11
    return True
  File "/usr/lib64/python3.4/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib64/python3.4/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/usr/lib64/python3.4/pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "/home/u1/.virtualenvs/npserver/lib/python3.4/site-packages/IPython/core/debugger.py", line 294, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/usr/lib64/python3.4/pdb.py", line 346, in interaction
    self._cmdloop()
  File "/usr/lib64/python3.4/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/usr/lib64/python3.4/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
nose.proxy.TypeError: bad argument type for built-in operation
-------------------- >> begin captured stdout << ---------------------
> /home/z/pproj/npserver_ssh/test/test_11.py(13)test11()
     11 def test11():
     12     import ipdb; ipdb.set_trace()
---> 13     return True
```

**Comment by gotcha** [comment]
Can you try with `ipdb.sset_trace` as documented in https://github.com/gotcha/ipdb#issues-with-stdout ?

**Comment by Fak3** [comment]
This one kinda worked for me on python3:
```
def test11():
    from ipdb import slaunch_ipdb_on_exception, set_trace, spm
    with slaunch_ipdb_on_exception():
        set_trace()
        spm()

    return True

```
But the trace is 7 calls deeper than actual set_trace().
```
  /home/z/pproj/npserver_ssh/test/test_11.py(15)test11()
     14         set_trace()
---> 15         spm()
     16 

  /usr/lib64/python3.4/bdb.py(48)trace_dispatch()
     47         if event == 'line':
---> 48             return self.dispatch_line(frame)
     49         if event == 'call':

  /usr/lib64/python3.4/bdb.py(66)dispatch_line()
     65         if self.stop_here(frame) or self.break_here(frame):
---> 66             self.user_line(frame)
     67             if self.quitting: raise BdbQuit

  /usr/lib64/python3.4/pdb.py(259)user_line()
    258         if self.bp_commands(frame):
--> 259             self.interaction(frame, None)
    260 

  /home/u1/.virtualenvs/npserver/lib/python3.4/site-packages/IPython/core/debugger.py(294)interaction()
    293             try:
--> 294                 OldPdb.interaction(self, frame, traceback)
    295                 break

  /usr/lib64/python3.4/pdb.py(346)interaction()
    345         self.print_stack_entry(self.stack[self.curindex])
--> 346         self._cmdloop()
    347         self.forget()

  /usr/lib64/python3.4/pdb.py(319)_cmdloop()
    318                 self.allow_kbdint = True
--> 319                 self.cmdloop()
    320                 self.allow_kbdint = False

> /usr/lib64/python3.4/cmd.py(126)cmdloop()
    125                         try:
--> 126                             line = input(self.prompt)
    127                         except EOFError:
```

On python2 it still looks like freeze. I can type 'c' and hit enter to continue after such freeze. Other commands like 'bt' or 'r' do nothing.

**Comment by Fak3** [comment]
Oh, I missed from the doc that the new function is called sset_trace() with double 's'. It worked for me on both python2 and python3.
```
import ipdb; ipdb.sset_trace()
```
I don't understand what does spm() function, mintioned in the doc. I didn't have to use it.
