### ISSUE TITLE
ipdb breaks shortly after pausing

### ISSUE THREAD

**Issue by StriveForBest** [gotcha/ipdb#166]
I have an `ipdb` statement inside of my very simple `post` method of the Class-Based Django View:

```python
def post(self, request, *args, **kwargs):
    super().post(*args, **kwargs)
    import ipdb; ipdb.set_trace()
```

Upon form submission, I see the execution pause on my `ipdb` line for a second and then crashing with the following traceback:

```shell
django-configurations version 2.1, using configuration 'Development'
INFO 2019-06-12 09:32:01,755 autoreload 4241 4455990720 Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 12, 2019 - 09:32:03
Django version 2.2.2, using settings 'fuweb.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
INFO 2019-06-12 09:33:10,516 basehttp 4241 123145442844672 "GET /account/ HTTP/1.1" 200 545557
> /Users/alex.zagoro/projects/gestalt/fuweb/fuweb/accounts/views.py(64)post()
     62         # ipdb.set_trace()
     63         ipdb.set_trace(context=5)
---> 64         return super().post(*args, **kwargs)
     65
     66         # form = self.get_form()

ipdb> Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 585, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 570, in start_django
    reloader.run(django_main_thread)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 288, in run
    self.run_loop()
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 294, in run_loop
    next(ticker)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 334, in tick
    for filepath, mtime in self.snapshot_files():
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 350, in snapshot_files
    for file in self.watched_files():
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 249, in watched_files
    yield from iter_all_python_module_files()
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 103, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/django/utils/autoreload.py", line 120, in iter_modules_and_files
    sys_file_paths.append(module.__file__)
AttributeError: module '__main__' has no attribute '__file__'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/IPython/core/history.py", line 780, in writeout_cache
    self._writeout_input_cache(conn)
  File "/Users/alex.zagoro/venv/fuweb-UZAlmVjd/lib/python3.7/site-packages/IPython/core/history.py", line 764, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145442844672 and this is thread id 4455990720.
```

I tried to move the import `ipdb` to a different method (`get_object`) and still getting the same behavior.

**Comment by alexey-sveshnikov** [comment]
This is a bug in Django (already fixed): https://code.djangoproject.com/ticket/30588
