### ISSUE TITLE
`import ipdb` stops multiprocessing from working

### ISSUE THREAD

**Issue by ppwwyyxx** [gotcha/ipdb#194]
```
import ipdb
import multiprocessing as mp

def main():
    print(1)

if __name__ == "__main__":
    mp = mp.get_context("spawn")
    p = mp.Process(target=main, daemon=False)
    p.start()
```

gives:
```
Traceback (most recent call last):
  File "train_net.py", line 19, in <module>
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function main at 0x7f85d1b981f0>: attribute lookup main on __main__ failed
```

works after removing `import ipdb`.

**Comment by RalphMao** [comment]
Any solution to this, or alternative to ipdb?

**Comment by ppwwyyxx** [comment]
@RalphMao I usually use this to debug a new process:
```
import multiprocessing as mp
import os, sys

def main():
    print(1)
    if True:  # if this process needs debug
         os.dup2(0, sys.stdin.fileno())
         import IPython as IP; IP.embed()

if __name__ == "__main__":
    mp = mp.get_context("spawn")
    p = mp.Process(target=main, daemon=False)
    p.start()
```
