### ISSUE TITLE
Django restarting can make it impossible to quit ipdb

### ISSUE THREAD

**Issue by stuaxo** [gotcha/ipdb#239]
If I have ipdb open while django automatically restarts (because I edited some code), it's impossible to even quit()  (I don't necessarily expect "continue" to work) it looks like the async loop cleanup gets a bit confused:

```
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/pyston3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/pyston3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/IPython/terminal/debugger.py", line 122, in in_thread
    line = self.pt_app.prompt()
  File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/usr/lib/pyston3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/application/application.py", line 798, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/application/application.py", line 952, in cancel_and_wait_for_background_tasks
    await task
RuntimeError: Task <Task pending name='Task-829' coro=<Application.run_async() running at /home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/application/application.py:816> cb=[_run_until_complete_cb() at /usr/lib/pyston3.8/asyncio/base_events.py:184]> got Future <Task pending name='Task-906' coro=<KeyProcessor._start_timeout.<locals>.wait() running at /home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/prompt_toolkit/key_binding/key_processor.py:406> wait_for=<Future cancelled>> attached to a different loop
```

**Comment by gotcha** [comment]
(Not a Django expert)

Is Django always using `pyston` or is that sthing you configure ?

My gut feeling is that this is an issue between `pyston` and `ipdb` (or IPython).

**Comment by stuaxo** [comment]
Good catch.

Using pyston instead of cpython was something I did.

I've upgraded it, and the issue seems to have gone - it had been so reliable up to that point I'd forgotten I was using it.
