### ISSUE TITLE
Using set_trace causes AttributeError

### ISSUE THREAD

**Issue by alanbernstein** [gotcha/ipdb#240]
`AttributeError: 'Namespace' object has no attribute '_flags'`

I am seeing this error any time I call `set_trace` on Mac (Big Sur, 11.6, intel), but not Ubuntu.

Other version information:

```
$ pip freeze | grep -i ipdb
ipdb==0.13.9

$ pip freeze | grep -i ipython
ipython==7.19.0
ipython-genutils==0.2.0

$ python3 --version
Python 3.9.8
```

Since this has not been reported previously, I wonder if it is some local environment issue, but I'm creating this in case it's not. Or if it is, maybe the root cause is more obvious to someone else; I'm not familiar with the traitlets library seen in the stack trace.

I can reproduce this with a minimal script:

```
from ipdb import set_trace
set_trace()
```

The full stack trace:

```
$ python3 ipdb-bug-reproducer.py
Traceback (most recent call last):
  File "/Users/alan/ipdb-bug-reproducer.py", line 2, in <module>
    set_trace()
  File "/usr/local/lib/python3.9/site-packages/ipdb/__main__.py", line 77, in set_trace
    p = _init_pdb(context).set_trace(frame)
  File "/usr/local/lib/python3.9/site-packages/ipdb/__main__.py", line 54, in _init_pdb
    debugger_cls = _get_debugger_cls()
  File "/usr/local/lib/python3.9/site-packages/ipdb/__main__.py", line 34, in _get_debugger_cls
    ipapp.initialize(["--no-term-title"])
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 308, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/IPython/core/application.py", line 450, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 303, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 708, in parse_command_line
    self.cli_config = deepcopy(loader.load_config())
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/loader.py", line 847, in load_config
    self._parse_args(argv)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/loader.py", line 906, in _parse_args
    self.parsed_data = self.parser.parse_args(to_parse)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1822, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/loader.py", line 770, in parse_known_args
    return super().parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1850, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2064, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2004, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1932, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/loader.py", line 931, in __call__
    namespace._flags.append(self.flag)
AttributeError: 'Namespace' object has no attribute '_flags'
```

**Comment by gotcha** [comment]
Which `IPython` version ? `ipdb` is a light wrapper around it.

**Comment by alanbernstein** [comment]
I originally saw this with ipython==7.19.0, also with 7.30.1 (latest at the moment) and 7.17.0 (the version in use on my Ubuntu machine that does not exhibit this behavior).

**Comment by gotcha** [comment]
I made a quick search and found this:

https://discourse.jupyter.org/t/attributeerror-namespace-object-has-no-attribute-flags-when-running-jupyter-kernelspec-list-json/11690

Which version of `traitlets` are you running ? They suggest that `traitlets==5.1.1` has a fix.

**Comment by alanbernstein** [comment]
Upgrading `traitlets` to 5.1.1 resolved this. Thank you!
