### ISSUE TITLE
AttributeError: 'TerminalPdb' object has no attribute '_runscript'

### ISSUE THREAD

**Issue by zjwilliams20** [gotcha/ipdb#264]
## Background

- OS: WSL2 Ubuntu 20.04
- `python` version: 3.11.1 via `pyenv`
- `ipython` version: 8.9.0
- `ipdb` version: 0.13.11

## Error
I'm getting this anytime I try to debug a python script. I don't see this when running 3.10, so that's probably related somehow.

```
❯ python -m ipdb align_reorder_.py
<frozen runpy>:128: RuntimeWarning: 'ipdb.__main__' found in sys.modules after import of package 'ipdb', but prior to execution of 'ipdb.__main__'; this may result in unpredictable behaviour
Traceback (most recent call last):
  File "/home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/ipdb/__main__.py", line 322, in main
    pdb._runscript(mainpyfile)
    ^^^^^^^^^^^^^^
AttributeError: 'TerminalPdb' object has no attribute '_runscript'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/ipdb/__main__.py(322)main()
    321                 else:
--> 322                     pdb._runscript(mainpyfile)
    323             if pdb._user_requested_quit:

ipdb> c
Traceback (most recent call last):
  File "/home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/ipdb/__main__.py", line 322, in main
    pdb._runscript(mainpyfile)
    ^^^^^^^^^^^^^^
AttributeError: 'TerminalPdb' object has no attribute '_runscript'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/ipdb/__main__.py", line 344, in <module>
    main()
  File "/home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/ipdb/__main__.py", line 338, in main
    pdb.interaction(None, t)
  File "/home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/IPython/core/debugger.py", line 335, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/home/zjw/.pyenv/versions/3.11.1/lib/python3.11/pdb.py", line 435, in interaction
    self._cmdloop()
  File "/home/zjw/.pyenv/versions/3.11.1/lib/python3.11/pdb.py", line 400, in _cmdloop
    self.cmdloop()
  File "/home/zjw/grad/ECE-549/env11/lib/python3.11/site-packages/IPython/terminal/debugger.py", line 141, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/home/zjw/.pyenv/versions/3.11.1/lib/python3.11/pdb.py", line 500, in onecmd
    return cmd.Cmd.onecmd(self, line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjw/.pyenv/versions/3.11.1/lib/python3.11/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/home/zjw/.pyenv/versions/3.11.1/lib/python3.11/pdb.py", line 1146, in do_continue
    self.set_continue()
  File "/home/zjw/.pyenv/versions/3.11.1/lib/python3.11/bdb.py", line 344, in set_continue
    self._set_stopinfo(self.botframe, None, -1)
                       ^^^^^^^^^^^^^
AttributeError: 'TerminalPdb' object has no attribute 'botframe'

If you suspect this is an IPython 8.9.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by zjwilliams20** [comment]
Looks like this will get resolved with the incoming PR that was mentioned above.
