### ISSUE TITLE
Python 3.4.2 installation error

### ISSUE THREAD

**Issue by wiliamsouza** [gotcha/ipdb#60]
Trying to install `ipdb` inside a `virtualenv` with Python 3.4.2 on a linux box.

Running `python setup.py  install` and `pip install ipdb` same result.

```
running install
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    use_2to3=True,
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wiliam/.virtualenvs/test/lib/python3.4/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/wiliam/.virtualenvs/test/lib/python3.4/site-packages/setuptools/command/install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/wiliam/.virtualenvs/test/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 283, in finalize_options
    'install_lib', ('install_dir', 'install_dir')
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/wiliam/.virtualenvs/test/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/wiliam/.pyenv/versions/3.4.2/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout
```

**Comment by toolforger** [comment]
I guess whatever the current version was on Dec 2014. `pip install -U` upgrades the package.
For me, it upgraded from `setuptools 12.2` to `setuptools-17.1.1-py2.py3-none-any.whl` .
