### ISSUE TITLE
crash on quitting set_trace():  _init_pdb() returns None

### ISSUE THREAD

**Issue by dzen** [gotcha/ipdb#95]
Hello,

On some occation when I put an `ipdb ; ipdb.set_trace()` into my code, I get a traceback :
Do I have a misconfiguration somewhere ? I tried to set the debug with `%config Application.verbose_crash=True` but It said:
```
ipdb> %config Application.verbose_crash=True
*** SyntaxError: invalid syntax
```
could I have a few help on this ? Thank you.
```
ipdb> ^D
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/db/migrations/executor.py", line 112, in migrate
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/db/migrations/executor.py", line 168, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/django/db/migrations/migration.py", line 162, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/home/benoit/Projects/blue/libelastic/libelastic/migrations.py", line 86, in database_backwards
    import ipdb; ipdb.set_trace()
  File "/home/benoit/.venv/bluecap/lib/python3.4/site-packages/ipdb/__main__.py", line 133, in set_trace
    p.shell.restore_sys_module_state()
AttributeError: 'NoneType' object has no attribute 'shell'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by gotcha** [comment]
was fixed in latest release, https://pypi.python.org/pypi/ipdb/0.9.3

can you check ?
